id: comet
name: Comet
description: A blazing fast and minimal Spotify client.
version: "0.1.0"
tagline: Minimal Spotify client
maintainer: g0ldyy
source: https://github.com/g0ldyy/comet
website: https://github.com/g0ldyy/comet
compose: docker-compose.yml
categories:
  - Media
