version: "3.7"
services:
  comet:
    image: ghcr.io/g0ldyy/comet:latest
    container_name: comet
    restart: unless-stopped
    ports:
      - "8080:8080"   # adjust if comet uses another port
    environment:
      - TZ=UTC
